# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'calcu.ui'
##
## Created by: Qt User Interface Compiler version 6.11.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QMainWindow,
    QMenuBar, QPushButton, QSizePolicy, QStatusBar,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(361, 588)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.outputLabel = QLabel(self.centralwidget)
        self.outputLabel.setObjectName(u"outputLabel")
        self.outputLabel.setGeometry(QRect(10, 10, 341, 91))
        font = QFont()
        font.setPointSize(36)
        self.outputLabel.setFont(font)
        self.outputLabel.setLocale(QLocale(QLocale.English, QLocale.Eritrea))
        self.outputLabel.setFrameShape(QFrame.Shape.Box)
        self.outputLabel.setFrameShadow(QFrame.Shadow.Raised)
        self.outputLabel.setLineWidth(2)
        self.outputLabel.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.outputLabel.setMargin(10)
        self.percentButton = QPushButton(self.centralwidget)
        self.percentButton.setObjectName(u"percentButton")
        self.percentButton.setGeometry(QRect(10, 110, 75, 75))
        font1 = QFont()
        font1.setPointSize(26)
        self.percentButton.setFont(font1)
        self.cButton = QPushButton(self.centralwidget)
        self.cButton.setObjectName(u"cButton")
        self.cButton.setGeometry(QRect(90, 110, 75, 75))
        self.cButton.setFont(font1)
        self.arrowButton = QPushButton(self.centralwidget)
        self.arrowButton.setObjectName(u"arrowButton")
        self.arrowButton.setGeometry(QRect(180, 110, 75, 75))
        self.arrowButton.setFont(font1)
        self.divideButton = QPushButton(self.centralwidget)
        self.divideButton.setObjectName(u"divideButton")
        self.divideButton.setGeometry(QRect(275, 110, 75, 75))
        self.divideButton.setFont(font1)
        self.sevenButton = QPushButton(self.centralwidget)
        self.sevenButton.setObjectName(u"sevenButton")
        self.sevenButton.setGeometry(QRect(10, 200, 75, 75))
        self.sevenButton.setFont(font1)
        self.eightButton = QPushButton(self.centralwidget)
        self.eightButton.setObjectName(u"eightButton")
        self.eightButton.setGeometry(QRect(90, 200, 75, 75))
        self.eightButton.setFont(font1)
        self.nineButton = QPushButton(self.centralwidget)
        self.nineButton.setObjectName(u"nineButton")
        self.nineButton.setGeometry(QRect(180, 200, 75, 75))
        self.nineButton.setFont(font1)
        self.multiplyButton = QPushButton(self.centralwidget)
        self.multiplyButton.setObjectName(u"multiplyButton")
        self.multiplyButton.setGeometry(QRect(270, 200, 75, 75))
        self.multiplyButton.setFont(font1)
        self.twoButton = QPushButton(self.centralwidget)
        self.twoButton.setObjectName(u"twoButton")
        self.twoButton.setGeometry(QRect(90, 370, 75, 75))
        self.twoButton.setFont(font1)
        self.oneButton = QPushButton(self.centralwidget)
        self.oneButton.setObjectName(u"oneButton")
        self.oneButton.setGeometry(QRect(10, 370, 75, 75))
        self.oneButton.setFont(font1)
        self.minusButton = QPushButton(self.centralwidget)
        self.minusButton.setObjectName(u"minusButton")
        self.minusButton.setGeometry(QRect(270, 290, 75, 75))
        self.minusButton.setFont(font1)
        self.sixButton = QPushButton(self.centralwidget)
        self.sixButton.setObjectName(u"sixButton")
        self.sixButton.setGeometry(QRect(180, 290, 75, 75))
        self.sixButton.setFont(font1)
        self.fourButton = QPushButton(self.centralwidget)
        self.fourButton.setObjectName(u"fourButton")
        self.fourButton.setGeometry(QRect(10, 290, 75, 75))
        self.fourButton.setFont(font1)
        self.fiveButton = QPushButton(self.centralwidget)
        self.fiveButton.setObjectName(u"fiveButton")
        self.fiveButton.setGeometry(QRect(90, 290, 75, 75))
        self.fiveButton.setFont(font1)
        self.threeButton = QPushButton(self.centralwidget)
        self.threeButton.setObjectName(u"threeButton")
        self.threeButton.setGeometry(QRect(180, 370, 75, 75))
        self.threeButton.setFont(font1)
        self.addButton = QPushButton(self.centralwidget)
        self.addButton.setObjectName(u"addButton")
        self.addButton.setGeometry(QRect(270, 370, 75, 75))
        self.addButton.setFont(font1)
        self.plusminusButton = QPushButton(self.centralwidget)
        self.plusminusButton.setObjectName(u"plusminusButton")
        self.plusminusButton.setGeometry(QRect(10, 450, 75, 75))
        self.plusminusButton.setFont(font1)
        self.zeroButton = QPushButton(self.centralwidget)
        self.zeroButton.setObjectName(u"zeroButton")
        self.zeroButton.setGeometry(QRect(90, 450, 75, 75))
        self.zeroButton.setFont(font1)
        self.decimalButton = QPushButton(self.centralwidget)
        self.decimalButton.setObjectName(u"decimalButton")
        self.decimalButton.setGeometry(QRect(190, 450, 75, 75))
        self.decimalButton.setFont(font1)
        self.equalButton = QPushButton(self.centralwidget)
        self.equalButton.setObjectName(u"equalButton")
        self.equalButton.setGeometry(QRect(270, 450, 75, 75))
        self.equalButton.setFont(font1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 361, 33))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"calculator", None))
        self.outputLabel.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.percentButton.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.cButton.setText(QCoreApplication.translate("MainWindow", u"C", None))
        self.arrowButton.setText(QCoreApplication.translate("MainWindow", u"<<", None))
        self.divideButton.setText(QCoreApplication.translate("MainWindow", u"/", None))
        self.sevenButton.setText(QCoreApplication.translate("MainWindow", u"7", None))
        self.eightButton.setText(QCoreApplication.translate("MainWindow", u"8", None))
        self.nineButton.setText(QCoreApplication.translate("MainWindow", u"9", None))
        self.multiplyButton.setText(QCoreApplication.translate("MainWindow", u"x", None))
        self.twoButton.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.oneButton.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.minusButton.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.sixButton.setText(QCoreApplication.translate("MainWindow", u"6", None))
        self.fourButton.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.fiveButton.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.threeButton.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.addButton.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.plusminusButton.setText(QCoreApplication.translate("MainWindow", u"+/-", None))
        self.zeroButton.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.decimalButton.setText(QCoreApplication.translate("MainWindow", u".", None))
        self.equalButton.setText(QCoreApplication.translate("MainWindow", u"=", None))
    # retranslateUi

